/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prog2.vista;

import java.awt.Component;
import prog2.adaptador.*;

/**
 *
 * @author Marina
 */
public class AppMercatUB extends javax.swing.JFrame {

    private Adaptador adaptador = new Adaptador();

    /**
     * Creates new form AppMercatUB
     */
    public AppMercatUB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtMenuMercatUB = new javax.swing.JTextField();
        btnGestioClients = new javax.swing.JButton();
        btnGestioArticles = new javax.swing.JButton();
        btnGestioComandes = new javax.swing.JButton();
        btnCarregarGuardarDades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMenuMercatUB.setBackground(new java.awt.Color(242, 242, 242));
        txtMenuMercatUB.setFont(new java.awt.Font("Kannada MN", 0, 13)); // NOI18N
        txtMenuMercatUB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMenuMercatUB.setText("MENU MERCAT UB");
        txtMenuMercatUB.setBorder(null);
        txtMenuMercatUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuMercatUBActionPerformed(evt);
            }
        });

        btnGestioClients.setText("Gestionar clients");
        btnGestioClients.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestioClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioClientsActionPerformed(evt);
            }
        });

        btnGestioArticles.setText("Gestionar articles");
        btnGestioArticles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestioArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioArticlesActionPerformed(evt);
            }
        });

        btnGestioComandes.setText("Gestionar comandes");
        btnGestioComandes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestioComandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioComandesActionPerformed(evt);
            }
        });

        btnCarregarGuardarDades.setText("Guardar / carregar dades");
        btnCarregarGuardarDades.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCarregarGuardarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarGuardarDadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(txtMenuMercatUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestioComandes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarregarGuardarDades)
                            .addComponent(btnGestioArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestioClients, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtMenuMercatUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestioClients)
                .addGap(24, 24, 24)
                .addComponent(btnGestioArticles)
                .addGap(18, 18, 18)
                .addComponent(btnGestioComandes)
                .addGap(18, 18, 18)
                .addComponent(btnCarregarGuardarDades)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMenuMercatUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuMercatUBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenuMercatUBActionPerformed

    private void btnGestioClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioClientsActionPerformed
        // TODO add your handling code here:
        DialogGestioClients gestioClientsFrame = new DialogGestioClients(this, true, this.adaptador);
        gestioClientsFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        gestioClientsFrame.setTitle("Gestio Clients");
        gestioClientsFrame.setVisible(true);
    }//GEN-LAST:event_btnGestioClientsActionPerformed

    private void btnGestioArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioArticlesActionPerformed
        // TODO add your handling code here:
        DialogGestioArticles gestioArticlesFrame = new DialogGestioArticles(this, true, this.adaptador);
        gestioArticlesFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        gestioArticlesFrame.setTitle("Gestio Articles");
        gestioArticlesFrame.setVisible(true);
    }//GEN-LAST:event_btnGestioArticlesActionPerformed

    private void btnGestioComandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioComandesActionPerformed
        // TODO add your handling code here:
        DialogGestioComandes gestioComandesFrame = new DialogGestioComandes(this, true, this.adaptador);
        gestioComandesFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        gestioComandesFrame.setTitle("Gestio Comandes");
        gestioComandesFrame.setVisible(true);
    }//GEN-LAST:event_btnGestioComandesActionPerformed

    private void btnCarregarGuardarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarGuardarDadesActionPerformed
        // TODO add your handling code here:
        DialogGuardarCarregarDades dialog = new DialogGuardarCarregarDades(this, true, adaptador);
        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dialog.setTitle("Nom del fitxer");
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnCarregarGuardarDadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMercatUB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarGuardarDades;
    private javax.swing.JButton btnGestioArticles;
    private javax.swing.JButton btnGestioClients;
    private javax.swing.JButton btnGestioComandes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField txtMenuMercatUB;
    // End of variables declaration//GEN-END:variables
}
