package prog2.vista;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import prog2.adaptador.*;

/**
 * Ventana en la que se elige un archivo para guardar o cargar los datos del
 * mercado.
 *
 * @author mariasanchez
 */
public class DialogGuardarCarregarDades extends javax.swing.JDialog {

    private Adaptador adaptador = new Adaptador();
    String nomFitxer;

    /**
     * Crea una instancia del DialogFileChooser.
     *
     * @param parent
     * @param modal
     * @param adaptador instacia de adaptador con los datos del mercado.
     */
    public DialogGuardarCarregarDades(java.awt.Frame parent, boolean modal, Adaptador adaptador) {
        super(parent, modal);
        initComponents();
        this.adaptador = adaptador;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brnGroupCarregaGuarda = new javax.swing.ButtonGroup();
        btnSelecciona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomFitxer = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSelecciona.setText("Selecciona");
        btnSelecciona.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSelecciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionaActionPerformed(evt);
            }
        });

        jLabel1.setText("Fitxer:");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        brnGroupCarregaGuarda.add(btnRecuperar);
        btnRecuperar.setText("Recuperar");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        brnGroupCarregaGuarda.add(btnGuardar);
        btnGuardar.setSelected(true);
        btnGuardar.setText("Guardar");

        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.setFont(new java.awt.Font("Kannada MN", 0, 13)); // NOI18N
        jTextField1.setText("Carrega o guarda les dades del Mercat UB");
        jTextField1.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNomFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelecciona, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecuperar)
                    .addComponent(btnGuardar))
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecciona)
                    .addComponent(txtNomFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Getter del adaptador.
     *
     * @return objeto de la clase Adaptador con los datos del mercado.
     */
    public Adaptador getAdaptador() {
        return this.adaptador;
    }

    /**
     * Abre una ventana para elegir el archivo en el que se quiere guardar los
     * datos o del que se quieren cargar.
     *
     * @param evt
     */
    private void btnSeleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionaActionPerformed
        File fitxer;
        //Creació del selector de fitxer
        JFileChooser seleccio = new JFileChooser();
        //Mostrem la finestra de dialeg
        //Resultat emmagazema una constant que indica si s’ha
        //seleccionat o no un fitxer
        int resultat = seleccio.showOpenDialog(this);
        //Assegurem que hi hagi un fitxer seleccionat
        if (resultat == JFileChooser.APPROVE_OPTION) {
            //Obtenim el fitxer
            fitxer = seleccio.getSelectedFile();
            //Posem la ruta del fitxer al quadre de text
            txtNomFitxer.setText(fitxer.toString());
        }

        nomFitxer = txtNomFitxer.getText();

    }//GEN-LAST:event_btnSeleccionaActionPerformed

    /**
     * Guarda o carga los datos según si ha seleccionado el radioButton de
     * guardar o el de cargar.
     *
     * @param evt
     */
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            if (btnGuardar.isSelected()) {
                adaptador.guardaDades(this.nomFitxer);
                this.dispose();
            } else if (btnRecuperar.isSelected()) {
                adaptador.recuperaDades(this.nomFitxer);
                this.dispose();
            }
        } catch (MercatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Atenció", INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(DialogGuardarCarregarDades.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecuperarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup brnGroupCarregaGuarda;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JRadioButton btnGuardar;
    private javax.swing.JRadioButton btnRecuperar;
    private javax.swing.JButton btnSelecciona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtNomFitxer;
    // End of variables declaration//GEN-END:variables
}
