/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package prog2.vista;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import prog2.adaptador.Adaptador;

/**
 * Ventana en la que se añaden artículos al mercado.
 *
 * @author arnau
 */
public class DialogAfegirComanda extends javax.swing.JDialog {

    private Adaptador adaptador;
    DefaultComboBoxModel model;

    /**
     * Constructor de DialogAfegirArticle
     *
     * @param parent
     * @param modal
     * @param adaptador instacia de adaptador con los datos del mercado.
     */
    public DialogAfegirComanda(java.awt.Dialog parent, boolean modal, Adaptador adaptador) {
        super(parent, modal);
        initComponents();
        this.adaptador = adaptador;
        omplirLlista("clients");
        omplirLlista("articles");
    }

    void omplirLlista(String tipus) {
        DefaultComboBoxModel object = new DefaultComboBoxModel();
        ArrayList<String> llista = (tipus == "clients") ? (adaptador.llistarClients()) : (adaptador.llistarArticles());
        for (String cosa : llista) {
            object.addElement(cosa);
        }
        if (tipus == "clients") {
            comboClients.setModel(object);
        } else {
            comboArticles.setModel(object);
        }
    }

    /**
     * Getter del adaptador.
     *
     * @return objeto de la clase Adaptador con los datos del mercado.
     */
    public Adaptador getAdaptador() {
        return this.adaptador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        client = new javax.swing.JLabel();
        article = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtQuantitat = new javax.swing.JTextPane();
        Quantitat = new javax.swing.JLabel();
        btnAccepta = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        chkUrgent = new javax.swing.JCheckBox();
        txtIntro = new javax.swing.JTextField();
        comboClients = new javax.swing.JComboBox<>();
        comboArticles = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nou article");

        client.setText("Client:");
        client.setEnabled(false);

        article.setText("Article:");
        article.setEnabled(false);

        jScrollPane3.setViewportView(txtQuantitat);

        Quantitat.setText("Quantitat:");
        Quantitat.setEnabled(false);

        btnAccepta.setText("Afegeix");
        btnAccepta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAccepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptaActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancel·la");
        btnCancela.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        chkUrgent.setText("Comanda Urgent");
        chkUrgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUrgentActionPerformed(evt);
            }
        });

        txtIntro.setBackground(new java.awt.Color(242, 242, 242));
        txtIntro.setFont(new java.awt.Font("Kannada MN", 0, 13)); // NOI18N
        txtIntro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIntro.setText("Introdueix les dades de la comanda");
        txtIntro.setBorder(null);

        comboClients.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboArticles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAccepta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtIntro, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkUrgent)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(client, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(article, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Quantitat, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(comboClients, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboArticles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(article, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboArticles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(Quantitat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkUrgent)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccepta)
                    .addComponent(btnCancela))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Añade un nuevo artículo a la lista de artículos del mercado. Recoge los
     * datos de los campos de texto y comprueba si se ha marcado la casilla de
     * si el nuevo artículo admite o no envíos urgentes. Si ya existe un
     * artículo con el id indicado, muestra un mensaje indicando el error y no
     * guarda el artículo.
     *
     * @param evt evento correspondiente a clicar sobre el botón aceptar.
     */
    private void btnAcceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptaActionPerformed
        if (txtQuantitat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Alguna casella és en blanc.", "Atenció", INFORMATION_MESSAGE);
            return;
        }
        try {
            adaptador.afegirComanda(comboArticles.getSelectedIndex(), comboClients.getSelectedIndex(), Integer.parseInt(txtQuantitat.getText()), chkUrgent.isSelected());
            this.dispose();
        } catch (NumberFormatException numberException) {
            JOptionPane.showMessageDialog(this, "El preu o temps d'enviament proporcionat no és vàlid.", "Atenció", INFORMATION_MESSAGE);
        } catch (MercatException mercatException) {
            JOptionPane.showMessageDialog(this, mercatException.getMessage(), "Atenció", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAcceptaActionPerformed

    /**
     * Cierra la ventana.
     *
     * @param evt evento correspondiente a clicar sobre el botón de cancelar.
     */
    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void chkUrgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUrgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkUrgentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quantitat;
    private javax.swing.JLabel article;
    private javax.swing.JButton btnAccepta;
    private javax.swing.JButton btnCancela;
    private javax.swing.JCheckBox chkUrgent;
    private javax.swing.JLabel client;
    private javax.swing.JComboBox<String> comboArticles;
    private javax.swing.JComboBox<String> comboClients;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtIntro;
    private javax.swing.JTextPane txtQuantitat;
    // End of variables declaration//GEN-END:variables
}
