/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package prog2.vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import prog2.adaptador.Adaptador;

/**
 * Ventana en la que se añaden artículos al mercado.
 *
 * @author arnau
 */
public class DialogAfegirClient extends javax.swing.JDialog {

    private Adaptador adaptador;
    DefaultComboBoxModel model;

    /**
     * Constructor de DialogAfegirArticle
     *
     * @param parent
     * @param modal
     * @param adaptador instacia de adaptador con los datos del mercado.
     */
    public DialogAfegirClient(java.awt.Dialog parent, boolean modal, Adaptador adaptador) {
        super(parent, modal);
        initComponents();
        this.adaptador = adaptador;
    }

    /**
     * Getter del adaptador.
     *
     * @return objeto de la clase Adaptador con los datos del mercado.
     */
    public Adaptador getAdaptador() {
        return this.adaptador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCorreu = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNom = new javax.swing.JTextPane();
        Nom = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAdreca = new javax.swing.JTextPane();
        Adreca = new javax.swing.JLabel();
        btnAccepta = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        ckPremium = new javax.swing.JCheckBox();
        txtIntro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nou article");

        correu.setText("Correu:");
        correu.setEnabled(false);

        jScrollPane1.setViewportView(txtCorreu);

        jScrollPane2.setViewportView(txtNom);

        Nom.setText("Nom:");
        Nom.setEnabled(false);

        jScrollPane3.setViewportView(txtAdreca);

        Adreca.setText("Adreça:");
        Adreca.setEnabled(false);

        btnAccepta.setText("Afegeix");
        btnAccepta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAccepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptaActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancel·la");
        btnCancela.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        ckPremium.setText("Premium");
        ckPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPremiumActionPerformed(evt);
            }
        });

        txtIntro.setBackground(new java.awt.Color(242, 242, 242));
        txtIntro.setFont(new java.awt.Font("Kannada MN", 0, 13)); // NOI18N
        txtIntro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIntro.setText("Introdueix les dades del client");
        txtIntro.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAccepta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtIntro)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckPremium)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Adreca, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(correu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(Adreca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ckPremium)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccepta)
                    .addComponent(btnCancela))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Añade un nuevo artículo a la lista de artículos del mercado. Recoge los
     * datos de los campos de texto y comprueba si se ha marcado la casilla de
     * si el nuevo artículo admite o no envíos urgentes. Si ya existe un
     * artículo con el id indicado, muestra un mensaje indicando el error y no
     * guarda el artículo.
     *
     * @param evt evento correspondiente a clicar sobre el botón aceptar.
     */
    private void btnAcceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptaActionPerformed
        boolean flagPremium = ckPremium.isSelected();
        if (txtCorreu.getText().equals("") || txtNom.getText().equals("") || txtAdreca.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Alguna casella és en blanc.", "Atenció", INFORMATION_MESSAGE);
            return;
        }
        try {
            adaptador.afegirClient(txtCorreu.getText(), txtNom.getText(), txtAdreca.getText(), flagPremium);
            this.dispose();
        } catch (NumberFormatException numberException) {
            JOptionPane.showMessageDialog(this, "El preu o temps d'enviament proporcionat no és vàlid.", "Atenció", INFORMATION_MESSAGE);
        } catch (MercatException mercatException) {
            JOptionPane.showMessageDialog(this, mercatException.getMessage(), "Atenció", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAcceptaActionPerformed

    /**
     * Cierra la ventana.
     *
     * @param evt evento correspondiente a clicar sobre el botón de cancelar.
     */
    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void ckPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckPremiumActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adreca;
    private javax.swing.JLabel Nom;
    private javax.swing.JButton btnAccepta;
    private javax.swing.JButton btnCancela;
    private javax.swing.JCheckBox ckPremium;
    private javax.swing.JLabel correu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txtAdreca;
    private javax.swing.JTextPane txtCorreu;
    private javax.swing.JTextField txtIntro;
    private javax.swing.JTextPane txtNom;
    // End of variables declaration//GEN-END:variables
}
