/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package prog2.vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import prog2.adaptador.Adaptador;

/**
 * Ventana en la que se añaden artículos al mercado.
 *
 * @author arnau
 */
public class DialogAfegirArticle extends javax.swing.JDialog {

    private Adaptador adaptador;
    DefaultComboBoxModel model;

    /**
     * Constructor de DialogAfegirArticle
     *
     * @param parent
     * @param modal
     * @param adaptador instacia de adaptador con los datos del mercado.
     */
    public DialogAfegirArticle(java.awt.Dialog parent, boolean modal, Adaptador adaptador) {
        super(parent, modal);
        initComponents();
        this.adaptador = adaptador;
    }

    /**
     * Getter del adaptador.
     *
     * @return objeto de la clase Adaptador con los datos del mercado.
     */
    public Adaptador getAdaptador() {
        return this.adaptador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtId = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNom = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPreu = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTempsEnviament = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        btnAccepta = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        ckAdmetUrgent = new javax.swing.JCheckBox();
        txtIntro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nou article");

        jLabel1.setText("ID:");
        jLabel1.setEnabled(false);

        jScrollPane1.setViewportView(txtId);

        jScrollPane2.setViewportView(txtNom);

        jLabel2.setText("Nom:");
        jLabel2.setEnabled(false);

        jScrollPane3.setViewportView(txtPreu);

        jLabel3.setText("Preu:");
        jLabel3.setEnabled(false);

        jScrollPane4.setViewportView(txtTempsEnviament);

        jLabel4.setText("Temps d'enviament:");
        jLabel4.setEnabled(false);

        btnAccepta.setText("Accepta");
        btnAccepta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAccepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptaActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancel·la");
        btnCancela.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        ckAdmetUrgent.setText("Admet enviament urgent");
        ckAdmetUrgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAdmetUrgentActionPerformed(evt);
            }
        });

        txtIntro.setBackground(new java.awt.Color(242, 242, 242));
        txtIntro.setFont(new java.awt.Font("Kannada MN", 0, 13)); // NOI18N
        txtIntro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIntro.setText("Introdueix les dades del article");
        txtIntro.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAccepta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckAdmetUrgent)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtIntro)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(ckAdmetUrgent)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccepta)
                    .addComponent(btnCancela))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Añade un nuevo artículo a la lista de artículos del mercado. Recoge los
     * datos de los campos de texto y comprueba si se ha marcado la casilla de
     * si el nuevo artículo admite o no envíos urgentes. Si ya existe un
     * artículo con el id indicado, muestra un mensaje indicando el error y no
     * guarda el artículo.
     *
     * @param evt evento correspondiente a clicar sobre el botón aceptar.
     */
    private void btnAcceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptaActionPerformed
        boolean flagUrgent = ckAdmetUrgent.isSelected();
        if (txtId.getText().equals("") || txtNom.getText().equals("") || txtPreu.getText().equals("") || txtTempsEnviament.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Alguna casella és en blanc.", "Atenció", INFORMATION_MESSAGE);
            return;
        }
        try {
            Float.parseFloat(txtPreu.getText());
            Integer.parseInt(txtTempsEnviament.getText());
            adaptador.afegirArticle(txtId.getText(), txtNom.getText(), Float.parseFloat(txtPreu.getText()), flagUrgent, Integer.parseInt(txtTempsEnviament.getText()));
            this.dispose();
        } catch (NumberFormatException numberException) {
            JOptionPane.showMessageDialog(this, "El preu o temps d'enviament proporcionat no és vàlid.", "Atenció", INFORMATION_MESSAGE);
        } catch (MercatException mercatException) {
            JOptionPane.showMessageDialog(this, mercatException.getMessage(), "Atenció", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAcceptaActionPerformed

    /**
     * Cierra la ventana.
     *
     * @param evt evento correspondiente a clicar sobre el botón de cancelar.
     */
    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void ckAdmetUrgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAdmetUrgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckAdmetUrgentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccepta;
    private javax.swing.JButton btnCancela;
    private javax.swing.JCheckBox ckAdmetUrgent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane txtId;
    private javax.swing.JTextField txtIntro;
    private javax.swing.JTextPane txtNom;
    private javax.swing.JTextPane txtPreu;
    private javax.swing.JTextPane txtTempsEnviament;
    // End of variables declaration//GEN-END:variables
}
